version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: ec-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: ec
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1"
      LANG: C.UTF-8
    volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3307:3306
  node:
    build: ./node
    container_name: ec-node
    environment:
      - NODE_OPTIONS="--max-old-space-size=20000"
    volumes:
      - ../payment:/EC/payment
      - ../order:/EC/order
      - ../web:/EC/web
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002

